[로이] Step-3 구현
codesquad-members-2023/be-java-ladder pull request #63
Opened 2023-03-08 19:13 UTC by lvalentine6

- 사용자가 잘못된 값을 입력하면 에러 메시지 출력 후 다시 입력을 받는 기능을 구현
인덴트 1을 유지하며 예외처리 하는 로직에 대해 고민을 많이 했지만 만족스럽지 않아서 더 고민해볼 예정입니다.
- 배열을 List로 바꾸는 요구사항을 방금 발견해서 계속 수정 하겠습니다.

2023-03-08 19:14 UTC, lvalentine6 commented
배열을 List로 바꾸는 요구사항을 방금 발견해서 계속 수정 하겠습니다.

2023-03-09 00:36 UTC, honux77 requested changes
더 수정해야 하니 CR 로 변경해 놓을게요.

2023-03-09 05:43 UTC, lvalentine6 commented
step-3 구현 완성 했습니다.

2023-03-09 07:36 UTC, honux77 commented on src/main/java/kr/codesquad/controller/ApplicationController.java
> +    public String validateName() {
메소드 이름에 비해 실제로 하는 일이 더 많네요. 적절한 이름을 고민해 보세요.

2023-03-09 07:36 UTC, honux77 commented on src/main/java/kr/codesquad/controller/ApplicationController.java
> +    public String validateNumber() {
```suggestion
    public int validateNumber() {
```
여기도 마찬가지고, 리턴 타입도 int 이면 어떨까요?

2023-03-09 07:42 UTC, honux77 commented on src/main/java/kr/codesquad/model/Ladder.java
> +        makeColumn(ladder, joinMemberQueue);
```suggestion
        makeColumn(ladder, joinMemberSplit);
```
만들어진 큐는 실제로는 makeColumn에서만 활용하니까 makeColumn 내부에서 만들어주면 어떨까요?

2023-03-09 07:43 UTC, honux77 commented on src/main/java/kr/codesquad/model/Ladder.java
> +        init(ladder, maxLadderHeight, joinMembersSplit.size());
```suggestion
        List<List<String>> ladder = init(maxLadderHeight, joinMembersSplit.size());
```

요것도 이렇게 줄일 수 있을 것 같아요.

2023-03-09 07:44 UTC, honux77 approved these changes

2023-03-09 07:45 UTC, honux77 commented
수고하셨습니다.

2023-03-09 07:45 UTC, merged